### ISSUE TITLE
RSS Feed

### ISSUE THREAD

**Issue by pieterclaerhout** [andyleclair/andyleclair.github.io#1]
Hi @andyleclair , any chance you can add an RSS feed for your website?

That makes it easier (for me) to follow.

Here are some resources on how to do this:

* https://elixirschool.com/blog/now-with-more-elixir
* https://danschultzer.com/posts/adding-xml-feeds-to-phoenix

**Comment by andyleclair** [comment]
I'm beyond flattered anyone would give a shit enough to ask for this! I will take a look and see what I can do. Thanks for the suggestion!

**Comment by andyleclair** [comment]
@pieterclaerhout done!
